Закинул данные, но не запускается
System.InvalidOperationException: The seed entity for entity type 'Company' cannot be added because it has the navigation 'Filials' set. To seed relationships,  add the entity seed to 'Filial' and specify the foreign key values {'CompanyId'}.